repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.79.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
        args: [ "--minimum-priority=LOW" ]  # tweak as needed

  - repo: https://github.com/aquasecurity/tfsec
    rev: v1.28.13
    hooks:
      - id: tfsec
        args: [ "--no-colour" ]

  # Optional: Enable if using Checkov (must install checkov separately)
  # - repo: https://github.com/bridgecrewio/checkov
  #   rev: 2.4.0
  #   hooks:
  #     - id: checkov
  #       args: ["--quiet"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
